language: c++
git:
  depth: 3
dist: xenial
cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check libjson-c-dev libxml2-dev libxml2-utils libc++-dev libc++abi-dev

matrix:
  include:
    ## Coverage test
    - compiler: gcc
      env: ENABLE="--enable-check --enable-gcov --enable-json --enable-xml"
      before_install:
        - pip install --user cpp-coveralls
        - sudo apt-get update -qq
        - sudo apt-get install -qq check libjson-c-dev libxml2-dev libxml2-utils
      after_success:
        - coveralls --exclude tests --exclude src/lexer.l --exclude src/lexer.c --exclude src/parser.c --exclude src/parser.y --exclude src/example.c --exclude src/util.c  --gcov-options '\-lp'

    ## Test C library with clang
    - compiler: clang
      env: ENABLE="--enable-check"

    ## test that configuration works for clang when JSON-C and XML are disabled (but present)
    - compiler: clang
      env: ENABLE="--enable-check --disable-json --disable-xml"
    - compiler: gcc
      env: ENABLE="--enable-check --disable-json --disable-xml"

before_script:
  - autoreconf -i
  - ./configure $ENABLE

script: make && make check

after_failure:
  - cat tests/test-api.log
  - cat tests/test-cli.log
